//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesProject.Models
{
    using ShoesProject.Utils;
    using System;
    using System.Collections.Generic;
    
    public partial class cart
    {
        public string id { get; set; }
        public string username { get; set; }
        public string idproduct { get; set; }
        public double price { get; set; }
        public int quantity { get; set; }
        public double totalcost { get; set; }
    
        public virtual sho sho { get; set; }
        public cart(string iMaSP)
        {

            using (ProjectWebBanGiayEntities db = new ProjectWebBanGiayEntities())
            {

                CreateRandomID cr = new CreateRandomID();
                this.id = cr.newIDCart();
                this.idproduct = iMaSP;
                this.quantity = 1;
                this.price = db.shoes.Find(iMaSP).price;
                this.totalcost = price * quantity;

            }
        }

        public cart(string idCart, string iMaSP, int quantity, string username)
        {

            using (ProjectWebBanGiayEntities db = new ProjectWebBanGiayEntities())
            {

                this.id = idCart;
                this.idproduct = iMaSP;
                this.username = username;
                this.quantity = quantity;
                this.price = db.shoes.Find(iMaSP).price;
                this.totalcost = price * quantity;

            }
        }


        public cart()
        {

        }
    }
}
