//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class option
    {
        public string id { get; set; }
        public string id_shoe { get; set; }
        public string color { get; set; }
        public int size { get; set; }
        public double price { get; set; }
        public int quantity { get; set; }
        public string img { get; set; }
    
        public virtual sho sho { get; set; }

        public option() { }

        public option(string id, string id_shoe, string color, int size, double price, int quantity, string img)
        {
            this.id = id;
            this.id_shoe = id_shoe;
            this.color = color;
            this.size = size;
            this.price = price;
            this.quantity = quantity;
            this.img = img;
        }
    }
}
